"""Serialize collected values into .env.local."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from configure_env._types import Section


def emit_env_local(
    path: Path,
    sections: list[Section],
    result: dict[str, str],
) -> None:
    """Write *result* into *path* grouped by *sections*.

    Variables present in *result* are written as ``NAME=value``.
    Variables not in *result* are written as ``# NAME=`` (commented out).
    """
    lines: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines.append(f"# Generated by tools/configure_env.py on {ts}")
    lines.append("# Re-run the script to update. Manual edits are preserved as defaults.")
    lines.append("")

    for section in sections:
        lines.append(f"# {section.heading}")
        for var in section.variables:
            value = result.get(var.name)
            if value:
                lines.append(f"{var.name}={value}")
            else:
                lines.append(f"# {var.name}=")
        lines.append("")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
