include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/Install.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/IOSBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/XcodeExport.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ArtifactVerify.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AscUpload.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MacOSBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MacOSPackage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MacOSSign.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MacOSVerify.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/MacOSAppStoreBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AndroidBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AndroidVerify.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AndroidUpload.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/LinuxPackage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ReleaseDistributables.cmake")

# Configures all deploy pipeline targets for the given app target.
function(configure_deploy_pipelines target)
    configure_install(${target})
    configure_ios_build(${target})
    configure_ios_package(${target})
    configure_ios_verify(${target})
    configure_ios_upload(${target})
    configure_macos_build(${target})
    configure_macos_package(${target})
    configure_macos_sign(${target})
    configure_macos_verify(${target})
    configure_macos_appstore_build(${target})
    configure_macos_appstore_package(${target})
    configure_macos_appstore_verify(${target})
    configure_macos_appstore_upload(${target})
    configure_android_build_aab(${target})
    configure_android_build_apk(${target})
    configure_android_verify_aab(${target})
    configure_android_verify_apk(${target})
    configure_android_upload_play(${target})
    configure_linux_package(${target})
    configure_release_distributables(${target})
endfunction()
