# tools/configure-env.ps1 — interactive wizard that writes .env.local
# with developer-specific SDK paths and signing credentials.

$ErrorActionPreference = "Stop"

$ScriptDir   = $PSScriptRoot
$ProjectRoot = Split-Path $ScriptDir -Parent
$EnvLocal    = Join-Path $ProjectRoot ".env.local"

# ── Load existing .env.local as defaults ─────────────────────────────────────
$Defaults = [ordered]@{}
if (Test-Path $EnvLocal) {
    Write-Host "[configure-env] Loading existing .env.local for defaults..." -ForegroundColor Cyan
    foreach ($line in Get-Content $EnvLocal) {
        if ($line -match '^\s*#' -or [string]::IsNullOrWhiteSpace($line)) { continue }
        $eqIdx = $line.IndexOf('=')
        if ($eqIdx -gt 0) {
            $key   = $line.Substring(0, $eqIdx)
            $value = $line.Substring($eqIdx + 1)
            $Defaults[$key] = $value
        }
    }
}

# ── Prompt helper ────────────────────────────────────────────────────────────
$Result = [ordered]@{}

function Prompt-Var {
    param(
        [string]$VarName,
        [string]$Description
    )
    $default = if ($Defaults.Contains($VarName)) { $Defaults[$VarName] } else { "" }

    if ($default) {
        $input = Read-Host "  $Description ($VarName) [$default]"
    } else {
        $input = Read-Host "  $Description ($VarName)"
    }
    if ([string]::IsNullOrWhiteSpace($input)) { $input = $default }

    # Soft path validation
    if ($input -and ($Description -match 'path|root|Root|PATH|ROOT')) {
        if (-not (Test-Path $input -ErrorAction SilentlyContinue)) {
            Write-Host "    Path does not exist yet: $input (continuing anyway)" -ForegroundColor Yellow
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($input)) {
        $script:Result[$VarName] = $input
    }
}

# ── Start ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "QtQuickTemplate - Developer Environment Configuration" -ForegroundColor White -BackgroundColor DarkBlue
Write-Host "Detected platform: Windows"
Write-Host "Values are written to .env.local (gitignored)."
Write-Host "Press Enter to keep the default shown in [brackets]."

# ── Qt SDK Paths ─────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "-- Qt SDK Paths --" -ForegroundColor White

Prompt-Var "QT_WINDOWS_ROOT" "Windows Qt SDK root (e.g. C:\Qt\6.10.2\msvc2022_64)"
Prompt-Var "QT_ANDROID_ROOT" "Android Qt SDK root (leave empty to skip)"
Prompt-Var "QT_HOST_ROOT"    "Host Qt root for cross-compilation (leave empty to skip)"

# Derive Qt6_DIR
if ($Result.Contains("QT_WINDOWS_ROOT")) {
    $Result["Qt6_DIR"] = "$($Result["QT_WINDOWS_ROOT"])\lib\cmake\Qt6"
    Write-Host "[configure-env] Derived Qt6_DIR=$($Result["Qt6_DIR"])" -ForegroundColor Cyan
}

# ── Android Signing ──────────────────────────────────────────────────────────
$hasAndroid = $Result.Contains("QT_ANDROID_ROOT") -or $Defaults.Contains("QT_ANDROID_ROOT")
if ($hasAndroid) {
    Write-Host ""
    Write-Host "-- Android Signing --" -ForegroundColor White

    Prompt-Var "ANDROID_KEYSTORE_PATH"     "Keystore file path"
    Prompt-Var "ANDROID_KEYSTORE_PASSWORD"  "Keystore password"
    Prompt-Var "ANDROID_KEY_ALIAS"          "Key alias"
    Prompt-Var "ANDROID_KEY_PASSWORD"       "Key password"

    Write-Host ""
    Write-Host "-- Google Play Upload --" -ForegroundColor White

    Prompt-Var "ANDROID_PLAY_SERVICE_ACCOUNT_FILE" "Play Console service account JSON path (leave empty to skip)"
}

# ── Write .env.local ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "-- Writing .env.local --" -ForegroundColor White

$lines = @()
$lines += "# Generated by tools/configure-env.ps1 on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')"
$lines += "# Re-run the script to update. Manual edits are preserved as defaults."
$lines += ""

# Qt SDK Paths
$qtVars = @("QT_WINDOWS_ROOT", "QT_ANDROID_ROOT", "QT_HOST_ROOT", "Qt6_DIR")
$hasQt = $false
foreach ($var in $qtVars) {
    if ($Result.Contains($var)) {
        if (-not $hasQt) { $lines += "# Qt SDK Paths"; $hasQt = $true }
        $lines += "$var=$($Result[$var])"
    }
}
if ($hasQt) { $lines += "" }

# Android Signing
$androidVars = @("ANDROID_KEYSTORE_PATH", "ANDROID_KEYSTORE_PASSWORD", "ANDROID_KEY_ALIAS", "ANDROID_KEY_PASSWORD", "ANDROID_PLAY_SERVICE_ACCOUNT_FILE")
$hasAndroidSigning = $false
foreach ($var in $androidVars) {
    if ($Result.Contains($var)) {
        if (-not $hasAndroidSigning) { $lines += "# Android Signing"; $hasAndroidSigning = $true }
        $lines += "$var=$($Result[$var])"
    }
}
if ($hasAndroidSigning) { $lines += "" }

$lines | Set-Content -Path $EnvLocal -Encoding UTF8

Write-Host "[configure-env] Wrote $EnvLocal" -ForegroundColor Green
Write-Host ""
Write-Host "You can now run builds with .\tools\run.ps1:"
Write-Host "  .\tools\run.ps1 cmake --preset <preset>         # configure"
Write-Host "  .\tools\run.ps1 cmake --build --preset <preset>  # build"
